resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 100
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 10
        eventConsumerBufferSize: 10
