resilience4j:
  logging:
    level:
      io.github.resilience4j: DEBUG
  circuitbreaker:
    instances:
      overnachtingCircuitBreaker:
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 10
  retry:
    instances:
      overnachtingRetry:
        maxAttempts: 5
        waitDuration: 500ms
      retryExceptions:
        - kong.unirest.UnirestException
server:
  port: 8081