@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(reiziger, "Reiziger", "Stelt de reis samen en boekt de reis")
Person(reisAgent, "ReisAgent", "Ondersteund een reiziger met het samen stellen van een reis")

System_Boundary(c1, "Triptop") {
    ContainerDb(db, "Database", "Sql/MongoDB??", "Slaat de reis(pakket) data op")
    Container(frontend, "Web Applicatie", "react", "Biedt een interface voor de reiziger en reisAgent")
    Container(backend, "Backend", "java SpringBoot", "Behandelt de bedrijfslogica en gegevensverwerking")
}

System_Ext(wireMock, "WireMock", "IdentityProvider")
System_Ext(tripAdvisor, "TripAdvisor", "Biedt activiteiten en restaurants aan")
System_Ext(trail, "Trail API", "Biedt wandelroutes aan")
System_Ext(mailGun, "MailGun", "Stuurt emails")
System_Ext(textFlow, "TextFlow SMS API", "Stuurt SMS-berichten en verifieert")
System_Ext(betalingsProvider, "BetalingsProvider(PayPal)", "Verwerkt betalingen")
System_Ext(maps, "GoogleMaps", "Weergeeft de wereld kaart en tooont locaties")
System_Ext(booking, "Booking.com", "Biedt overnachtingen aan")
System_Ext(omio, "Omio", "Biedt vluchten, veerboten, treinen en bussen aan")

Rel(frontend, trail, "Haalt informatie op", "JSON/HTTPS")
Rel(frontend, tripAdvisor, "Haalt informatie op", "JSON/HTTPS")
Rel(frontend, backend, "Geeft data voor reizen en api verzoeken door")
Rel(frontend, maps, "Haalt een eyemap op", "Wat voor data is een een eyemap?")

Rel(backend, db, "Verstuurt reis(pakket) data")
Rel(backend, wireMock, "Logt in", "JSON/HTTPS")
Rel(backend, mailGun, "Versturen email", "JSON/HTTPS")
Rel(backend, textFlow, "Versturen SMS", "JSON/HTTPS?")
Rel(backend, betalingsProvider, "Versturen betaalverzoeken", "JSON/HTTPS?")
Rel(backend, omio, "Haalt informatie op en koopt tickets", "JSON/HTTPS?")
Rel(backend, booking, "Zoekt en boekt overnachtingen aan", "JSON/HTTPS?")

Rel(reiziger, frontend, "Stelt een reis samen en boekt deze")
Rel(reisAgent, frontend, "Assisteert reiziger en bouwt reispakketten")

@enduml