@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(trailController, "trailController", "Java Spring", "?")
Component(trailService, "trailService", "Java Spring", "?")
Component(trailData, "trail data fetch/process", "Java Spring", "Repository en DAO")
Container(trail, "Trail")

Rel(controller, trail, "probleem: krijgt geen waardevolle input terug")


@enduml