@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(reiziger, "Reiziger", "Stelt de reis samen en boekt de reis")
Person(reisAgent, "ReisAgent", "Ondersteund een reiziger met het samen stellen van een reis")



System_Ext(wireMock, "WireMock", "IdentityProvider")
System_Ext(tripAdvisor, "TripAdvisor", "Biedt hotels, vluchten, restaurants en auto's aan")
System_Ext(trail, "Trail API", "Biedt wandelroutes aan")
System_Ext(mailGun, "MailGun", "Stuurt emails")
System_Ext(textFlow, "TextFlow SMS API", "Stuurt SMS-berichten en verifieert")
System_Ext(betalingsProvider, "BetalingsProvider(PayPal)", "Verwerkt betalingen")

System_Boundary(c1, "test") {
    ContainerDb(db, "Database", "?", "Slaat de reis(pakket) data op")
    Container(frontend, "Web Applicatie", "react", "Interface voor de reiziger en reisAgent" )
    Container(backend, "Backend", "java", "Behandelt de bedrijfslogica en gegevensverwerking")
    Container(api, "api", "node.js", "?")
}

Rel(frontend, trail, "Haalt bouwsteen informatie op")
Rel(frontend, tripAdvisor, "Haalt bouwsteen informatie op")

Rel(api, wireMock, "Logt in", "JSON/HTTPS")
Rel(api, mailGun, "Versturen email", "JSON/HTTPS")
Rel(api, textFlow, "Versturen SMS")
Rel(api, betalingsProvider, "Verstuurt betaalverzoeken")

Rel(frontend, backend, "Geeft data voor reizen door")

Rel(backend, api, "?")
Rel(backend, db, "Verstuurt reis(pakket) data")

Rel(reiziger, frontend, "?")
Rel(reisAgent, frontend, "?")

@enduml