@startuml class diagram

class VluchtController {
    - VluchtService vluchtService
    + List<Vlucht> zoekVluchten(String vertrek, String bestemming, Date datum)
    + List<Vlucht> haalVluchtenOp(String username)
    + void boekVlucht(Vlucht vlucht)
}

class VluchtService {
    - VluchtRepository vluchtRepository
    - List<IExternVluchtAdapter> adapters
    + List<Vlucht> zoekVluchten(String vertrek, String bestemming, Date datum)
    + List<Vlucht> haalVluchtenOp(String username)
    + void boekVlucht(Vlucht vlucht)
}

interface IExternVluchtAdapter {
    + List<Vlucht> zoekVluchten(String vertrek, String bestemming, Date datum);
    + void boekVlucht(Vlucht vlucht);
}

class KLMAdapter implements IExternVluchtAdapter {
    + List<Vlucht> zoekVluchten(String vertrek, String bestemming, Date datum)
    + void boekVlucht(Vlucht vlucht)
}

class SkyscannerAdapter implements IExternVluchtAdapter {
    + List<Vlucht> zoekVluchten(String vertrek, String bestemming, Date datum)
    + void boekVlucht(Vlucht vlucht)
}

class VluchtRepository {
    + void slaOp(Vlucht vlucht, String username)
    + List<Vlucht> haalVluchtenOp(String username)
}

class Vlucht {
    - vluchtNummer: String
    - maatschappij: String
    - vertrekLocatie: String
    - bestemming: String
    - vertrekDatum: Date
    - prijs: double
    - vertrekDatumTijd: LocalDateTime
    - aankomstDatumTijd: LocalDateTime
}

VluchtController --> VluchtService : 1..1
VluchtService --> VluchtRepository : 1..1
VluchtService --> IExternVluchtAdapter : 1..*

'Om het diagram duidelijk te houden zijn deze relaties niet gemaakt:

'VluchtService --> Vlucht : 1..*
'VluchtController --> Vlucht : 1..*
'VluchtRepository --> Vlucht : 1..*
'IExternVluchtAdapter --> Vlucht : 1..*

@enduml