@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(bakka, "bakka")
ComponentDb(db, "db")

Component_Ext(api, "api")

Rel(bakka, db, "ja zo")

@enduml