@startuml

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(backend, "Backend", "Spring Boot", "Behandelt de bedrijfslogica")

System_Boundary(c1, "component") {
Component(service, "TripService", "Java Class", "Beheert het reis(pakket)")
Component(altHotelService, "AlternativesServiceHotel", "Java Class", "Biedt alternatieve hotels aan")
Component(availHotelService, "AvailabilityServiceHotel", "Java Class", "Checkt beschikbaarheid hotels")

}

Container(bookingAPI, "bookingAPI", "Java Class", "Communiceert met Booking.com of AirBnB")

Rel(backend, service, "Gebruikt")
Rel(service, availHotelService, "Checkt beschikbaarheid")
Rel(availHotelService, bookingAPI, "Vraagt beschikbaarheid op")
Rel(service, altHotelService, "Vraagt alternatieven *indien geen beschikbaarheid*", "Alleen als fallback")

@enduml


